field: c6a6830e-daad-4ac0-b66c-2f7628175116
fieldLayouts:
  497314f8-6f6a-486b-9d95-9df75bc02b02:
    tabs:
      -
        fields:
          087caacf-98c3-409b-873c-c4dadecfe3d7:
            required: false
            sortOrder: 2
          b5f7ba6a-6604-44ef-9760-b8b75758bd1d:
            required: false
            sortOrder: 1
          b6b1ac81-91e3-4e12-9337-c06be978aa6a:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  087caacf-98c3-409b-873c-c4dadecfe3d7:
    contentColumnType: string
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Email
  b5f7ba6a-6604-44ef-9760-b8b75758bd1d:
    contentColumnType: text
    fieldGroup: null
    handle: person
    instructions: ''
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b6b1ac81-91e3-4e12-9337-c06be978aa6a:
    contentColumnType: text
    fieldGroup: null
    handle: department
    instructions: ''
    name: Department
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: person
name: Person
sortOrder: 1
