field: 2d0f3f24-2560-4fff-8d6b-79339340c49a
fieldLayouts:
  11945b1e-e455-4015-b4ba-d12bd62903dc:
    tabs:
      -
        elements:
          -
            fieldUid: dcfd1b82-d516-46c2-adf7-768433cae2e9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d39a054-a39e-47f1-8d33-9449758b7a98
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d39a054-a39e-47f1-8d33-9449758b7a98:
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Custom.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  dcfd1b82-d516-46c2-adf7-768433cae2e9:
    contentColumnType: text
    fieldGroup: null
    handle: subheader
    instructions: ''
    name: Subheader
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subheader
name: Subheader
sortOrder: 2
