contentColumnType: text
fieldGroup: 04b3b4bb-5a04-4d55-a1fc-39e4312e4e96
handle: agency
instructions: ''
name: Agency
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
