contentColumnType: text
fieldGroup: 3fc14f6c-ba8d-46bd-b8fc-759a5beed7f4
handle: collaborators
instructions: ''
name: Collaborators
searchable: false
settings:
  addRowLabel: 'Add a collaborator'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Collaborator
            -
              - handle
              - collaborator
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Link
            -
              - handle
              - link
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
