contentColumnType: text
fieldGroup: 0da37b13-2d77-4500-8d1f-377fbac8ae30
handle: companyVat
instructions: ''
name: 'Company VAT'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
