contentColumnType: string
fieldGroup: 04b3b4bb-5a04-4d55-a1fc-39e4312e4e96
handle: producer
instructions: ''
name: Producer
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:5c2fa1b4-b6c4-4857-bfb3-0a7c2ef1d908'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
