contentColumnType: text
fieldGroup: 339d4aee-ce38-4262-8048-c7399da71ed7 # Talent
handle: stillsText
instructions: 'Text to use on talent page'
name: 'Stills Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
