fieldLayouts:
  d04da4a1-a462-461d-98d1-0f76c52c8ad5:
    tabs:
      -
        elements:
          -
            fieldUid: 28783b89-1d51-4d32-8712-32508354212a # Primary Talent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Primary Talent'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7d4244b7-bad7-45af-9f3b-e48a1a4937e6 # Associated Talent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Associated Talent'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: a3a6f62e-5498-4e0f-b65f-56ac02861128 # Director Talent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Directors
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 649d7b89-fd10-410e-b372-5c68ddfb957b # Photographer Talent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Photographers
        sortOrder: 4
handle: talent
name: Talent
